### ISSUE TITLE
Pull request ?

### ISSUE THREAD

**Issue by SwithFr** [Programmation-Cote-Serveur/mini-blog#1]
Juste pour savoir si on a le droit de faire des pull request sur ce dépôt si on a une suggestion à proposer ?

**Comment by dominiquevilain** [comment]
On a toujours le droit de faire des pull request. Mais si c’est pour intégrer les namespaces, c’est non. Je l’ai fait dans une version à la maison, mais ça sort de la ligne que je me fixe pour le cours. Ce sera peut-être un bonus.
N’oublie pas que l’objectif n’est pas forcément de faire le meilleur produit possible. J’ai des objectifs de formation que je dois adapter à mon public, très très varié…

**Comment by SwithFr** [comment]
Ok, c'était simplement pour savoir, je n'ai pas l'intention d'en faire pour le moment mais au cas ou, on ne sait jamais. 

Merci.

**Comment by dominiquevilain** [comment]
Sans problème, sens-toi libre de le faire :-)
